### ISSUE TITLE
import torchkeras报错

### ISSUE THREAD

**Issue by T-Atlas** [lyhue1991/torchkeras#11]
提示torchkeras No module named 'accelerate'
pip安装accelerate后
提示AttributeError: module 'signal' has no attribute 'SIGKILL'

我的环境是window，py3.9.13，torchkeras3.2.5

**Comment by T-Atlas** [comment]
seeing https://github.com/huggingface/accelerate/issues/817

**Comment by T-Atlas** [comment]
https://github.com/pytorch/pytorch/issues/85427

**Comment by hamind** [comment]
你好，我也遇到了这个问题，将torch从1.13.0降级就可以正常import了嘛

**Comment by T-Atlas** [comment]
> 

@hamind 是的，你也可以使用`pip install -U git+https://github.com/huggingface/accelerate`获得最新版本（**accelerate-0.14.0.dev0**）的accelerate以解决问题。你也可以使用**v0.12.0**的accelerate。可以参考https://github.com/huggingface/accelerate/issues/817
