### ISSUE TITLE
多gpu报错

### ISSUE THREAD

**Issue by bjmajic** [lyhue1991/torchkeras#19]
代码：官方给的实例
https://www.kaggle.com/code/lyhue1991/torchkeras-ddp-tpu-examples/notebook

运行环境：
pycharm 上的 run 按钮

报错信息：
![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=8916258777225389677 skey=@crypt_e053f7e0_aa31e901335d7fb7f47c2f0af8ecc9d4 mmweb_appid=wx_webfilehelper](https://github.com/lyhue1991/torchkeras/assets/18397336/71ea7a7c-ffdd-476d-9fd3-58bd0c6adf24)

**Comment by lyhue1991** [comment]
估计是windows环境对multiprocess的支持不够导致的~
你可以先跑一下这个纯accelerate的例子试试。
https://www.kaggle.com/code/lyhue1991/kaggle-ddp-tpu-examples

**Comment by bjmajic** [comment]
是Linux环境，远程开发

**Comment by CRonaldo1997** [comment]
去掉device_map='auto'即可
