### ISSUE TITLE
Expected all tensors to be on the same device, but found at least two devices, cuda:3 and cuda:0!  (when checking argument for argument target in method wrapper_CUDA_nll_loss_forward

### ISSUE THREAD

**Issue by amwork2020** [lyhue1991/torchkeras#20]
我在多gpu 运行您的examples/ChatGLM2——transformers.ipynb 的训练脚本，报 如下错误：
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:3 and cuda:0! 
(when checking argument for argument target in method wrapper_CUDA_nll_loss_forward)
in <module>:1                                                                                    │
│                                                                                                  │
│ ❱ 1 keras_model.fit(train_data = dl_train,                                                       │
│   2 │   │   │   │   val_data = dl_val,                                                           │
│   3 │   │   │   │   epochs=100,patience=5,                                                       │
│   4 │   │   │   │   monitor='val_loss',mode='min',                                               │
│                                                                                                  │
│ /u01/liuys/anaconda3/envs/chatglm/lib/python3.11/site-packages/torchkeras/kerasmodel.py:204 in   │
│ fit                                                                                              │
│                                                                                                  │
│   201 │   │   │                                                                                  │
│   202 │   │   │   train_epoch_runner = self.EpochRunner(train_step_runner,should_quiet)          │
│   203 │   │   │   train_metrics = {'epoch':epoch}                                                │
│ ❱ 204 │   │   │   train_metrics.update(train_epoch_runner(train_dataloader))                     │
│   205 │   │   │                                                                                  │
│   206 │   │   │   for name, metric in train_metrics.items():                                     │
│   207 │   │   │   │   self.history[name] = self.history.get(name, []) + [metric]                 │
│                                                                                                  │
│ /u01/liuys/anaconda3/envs/chatglm/lib/python3.11/site-packages/torchkeras/kerasmodel.py:77 in    │
│ __call__                                                                                         │
│                                                                                                  │
│    74 │   │                                                                                      │
│    75 │   │   for step, batch in loop:                                                           │
│    76 │   │   │   with self.accelerator.accumulate(self.net):                                    │
│ ❱  77 │   │   │   │   step_losses,step_metrics = self.steprunner(batch)                          │
│    78 │   │   │   │   step_log = dict(step_losses,**step_metrics)                                │
│    79 │   │   │   │   for k,v in step_losses.items():                                            │
│    80 │   │   │   │   │   epoch_losses[k] = epoch_losses.get(k,0.0)+v                            │
│                                                                                                  │
│ in __call__:20                                                                                   │
│                                                                                                  │
│   17 │   │                                                                                       │
│   18 │   │   #loss                                                                               │
│   19 │   │   with self.accelerator.autocast():                                                   │
│ ❱ 20 │   │   │   loss = self.net(input_ids=batch["input_ids"],labels=batch["labels"]).loss       │
│   21 │   │                                                                                       │
│   22 │   │   #backward()                                                                         │
│   23 │   │   if self.optimizer is not None and self.stage=="train":                              │
│                                                                                                  │
│ /u01/liuys/anaconda3/envs/chatglm/lib/python3.11/site-packages/torch/nn/modules/module.py:1501   │
│ in _call_impl                                                                                    │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ /u01/liuys/anaconda3/envs/chatglm/lib/python3.11/site-packages/accelerate/utils/operations.py:52 │
│ 1 in forward                                                                                     │
│                                                                                                  │
│   518 │   model_forward = ConvertOutputsToFp32(model_forward)                                    │
│   519 │                                                                                          │
│   520 │   def forward(*args, **kwargs):                                                          │
│ ❱ 521 │   │   return model_forward(*args, **kwargs)                                              │
│   522 │                                                                                          │
│   523 │   # To act like a decorator so that it can be popped when doing `extract_model_from_pa   │
│   524 │   forward.__wrapped__ = model_forward                                                    │
│                                                                                                  │
│ /u01/liuys/anaconda3/envs/chatglm/lib/python3.11/site-packages/accelerate/utils/operations.py:50 │
│ 9 in __call__                                                                                    │
│                                                                                                  │
│   506 │   │   update_wrapper(self, model_forward)                                                │
│   507 │                                                                                          │
│   508 │   def __call__(self, *args, **kwargs):                                                   │
│ ❱ 509 │   │   return convert_to_fp32(self.model_forward(*args, **kwargs))                        │
│   510 │                                                                                          │
│   511 │   def __getstate__(self):                                                                │
│   512 │   │   raise pickle.PicklingError(                                                        │
│                                                                                                  │
│ /u01/liuys/anaconda3/envs/chatglm/lib/python3.11/site-packages/torch/amp/autocast_mode.py:14 in  │
│ decorate_autocast                                                                                │
│                                                                                                  │
│    11 │   @functools.wraps(func)                                                                 │
│    12 │   def decorate_autocast(*args, **kwargs):                                                │
│    13 │   │   with autocast_instance:                                                            │
│ ❱  14 │   │   │   return func(*args, **kwargs)                                                   │
│    15 │   decorate_autocast.__script_unsupported = '@autocast() decorator is not supported in    │
│    16 │   return decorate_autocast                                                               │
│    17                                                                                            │
│                                                                                                  │
│ /u01/liuys/anaconda3/envs/chatglm/lib/python3.11/site-packages/peft/peft_model.py:686 in forward │
│                                                                                                  │
│    683 │   ):                                                                                    │
│    684 │   │   peft_config = self.active_peft_config                                             │
│    685 │   │   if not isinstance(peft_config, PromptLearningConfig):                             │
│ ❱  686 │   │   │   return self.base_model(                                                       │
│    687 │   │   │   │   input_ids=input_ids,                                                      │
│    688 │   │   │   │   attention_mask=attention_mask,                                            │
│    689 │   │   │   │   inputs_embeds=inputs_embeds,                                              │
│                                                                                                  │
│ /u01/liuys/anaconda3/envs/chatglm/lib/python3.11/site-packages/torch/nn/modules/module.py:1501   │
│ in _call_impl                                                                                    │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ /u01/liuys/anaconda3/envs/chatglm/lib/python3.11/site-packages/accelerate/hooks.py:165 in        │
│ new_forward                                                                                      │
│                                                                                                  │
│   162 │   │   │   with torch.no_grad():                                                          │
│   163 │   │   │   │   output = old_forward(*args, **kwargs)                                      │
│   164 │   │   else:                                                                              │
│ ❱ 165 │   │   │   output = old_forward(*args, **kwargs)                                          │
│   166 │   │   return module._hf_hook.post_forward(module, output)                                │
│   167 │                                                                                          │
│   168 │   module.forward = new_forward                                                           │
│                                                                                                  │
│ /u01/liuys/.cache/huggingface/modules/transformers_modules/THUDM/chatglm2-6b/c57e892806dfe383cd5 │
│ caf09719628788fe96379/modeling_chatglm.py:957 in forward                                         │
│                                                                                                  │
│    954 │   │   │   shift_labels = labels[..., 1:].contiguous()                                   │
│    955 │   │   │   # Flatten the tokens                                                          │
│    956 │   │   │   loss_fct = CrossEntropyLoss(ignore_index=-100)                                │
│ ❱  957 │   │   │   loss = loss_fct(shift_logits.view(-1, shift_logits.size(-1)), shift_labels.v  │
│    958 │   │   │                                                                                 │
│    959 │   │   │   lm_logits = lm_logits.to(hidden_states.dtype)                                 │
│    960 │   │   │   loss = loss.to(hidden_states.dtype)                                           │
│                                                                                                  │
│ /u01/liuys/anaconda3/envs/chatglm/lib/python3.11/site-packages/torch/nn/modules/module.py:1501   │
│ in _call_impl                                                                                    │
│                                                                                                  │
│   1498 │   │   if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks   │
│   1499 │   │   │   │   or _global_backward_pre_hooks or _global_backward_hooks                   │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                   │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                          │
│   1502 │   │   # Do not call functions when jit is used                                          │
│   1503 │   │   full_backward_hooks, non_full_backward_hooks = [], []                             │
│   1504 │   │   backward_pre_hooks = []                                                           │
│                                                                                                  │
│ /u01/liuys/anaconda3/envs/chatglm/lib/python3.11/site-packages/torch/nn/modules/loss.py:1174 in  │
│ forward                                                                                          │
│                                                                                                  │
│   1171 │   │   self.label_smoothing = label_smoothing                                            │
│   1172 │                                                                                         │
│   1173 │   def forward(self, input: Tensor, target: Tensor) -> Tensor:                           │
│ ❱ 1174 │   │   return F.cross_entropy(input, target, weight=self.weight,                         │
│   1175 │   │   │   │   │   │   │      ignore_index=self.ignore_index, reduction=self.reduction,  │
│   1176 │   │   │   │   │   │   │      label_smoothing=self.label_smoothing)                      │
│   1177                                                                                           │
│                                                                                                  │
│ /u01/liuys/anaconda3/envs/chatglm/lib/python3.11/site-packages/torch/nn/functional.py:3029 in    │
│ cross_entropy                                                                                    │
│                                                                                                  │
│   3026 │   │   )                                                                                 │
│   3027 │   if size_average is not None or reduce is not None:                                    │
│   3028 │   │   reduction = _Reduction.legacy_get_string(size_average, reduce)                    │
│ ❱ 3029 │   return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(re  │
│   3030                                                                                           │
│   3031                                                                                           │
│   3032 def binary_cross_entropy(

**Comment by lyhue1991** [comment]
你试试在env设置成只有一个cuda可见试试。

或者也可以把这两行改成False试试。

<img width="713" alt="image" src="https://github.com/lyhue1991/torchkeras/assets/30676974/49be789a-2296-4915-8cfa-88271a78ff6f">
