### ISSUE TITLE
deepspeed是否支持？

### ISSUE THREAD

**Issue by xxm1668** [lyhue1991/torchkeras#21]
我魔改了一下，不支持呢

**Comment by lyhue1991** [comment]
accelerate支持的，torchkeras原理上都是支持的。你可以看看accelerate库里的这段

<img width="880" alt="image" src="https://github.com/lyhue1991/torchkeras/assets/30676974/4eaa5ec6-f7a8-4b38-823e-2f0df6ab2310">

**Comment by xxm1668** [comment]
好的，多谢

**Comment by lyhue1991** [comment]
accelerate是支持deepspeed的，需要你根据
