### ISSUE TITLE
UnboundLocalError: local variable 'epoch_log' referenced before assignment

### ISSUE THREAD

**Issue by ChaohuaZhang** [lyhue1991/torchkeras#22]
![image](https://github.com/lyhue1991/torchkeras/assets/65476824/33ce4b3f-5e33-45ec-834a-76ef4d5840f1)

**Comment by ChaohuaZhang** [comment]
这个怎么解决

**Comment by CRonaldo1997** [comment]
如果你是在finetune ChatGLM2，试着去掉这句：
dl_train.size = 300

**Comment by lyhue1991** [comment]
看的哪个范例呢? kerasmodel.py的源码不长，遇到问题的话可以自己试着打印log调试一下
