### ISSUE TITLE
用ChatGLM2-transformers.ipynb和waimai_10k.csv微调模型不收敛

### ISSUE THREAD

**Issue by CRonaldo1997** [lyhue1991/torchkeras#23]
![image](https://github.com/lyhue1991/torchkeras/assets/24342998/11f1481f-4300-4ac9-ad13-37e2abe00e9b)
代码和数据都没改过，看起来没有要收敛的意思，求大神指点

**Comment by lyhue1991** [comment]
你用的是最新的torchkeras版本吗，你试试基础范例能够跑通吗？
https://github.com/lyhue1991/torchkeras/blob/master/01%EF%BC%8Ckerasmodel_example.ipynb

**Comment by CRonaldo1997** [comment]
> 你用的是最新的torchkeras版本吗，你试试基础范例能够跑通吗？ https://github.com/lyhue1991/torchkeras/blob/master/01%EF%BC%8Ckerasmodel_example.ipynb

已解决，我这边数据的问题，谢谢！
