### ISSUE TITLE
model.enable_input_require_grads() 报错

### ISSUE THREAD

**Issue by KMnO4-zx** [lyhue1991/torchkeras#25]
![1](https://github.com/lyhue1991/torchkeras/assets/77671993/db7fa2f8-57ef-4a4a-b93d-7f9937c58606)
![image](https://github.com/lyhue1991/torchkeras/assets/77671993/4fbd99e0-e2fa-424b-927c-219d90b4c6e0)

这个它没报错误原因，看不出来咋回事，大佬可以协助解决嘛？

**Comment by lyhue1991** [comment]
应该是版本的问题，更新一下peft。

**Comment by lyhue1991** [comment]
应该是版本的问题，更新一下transformers试试
