### ISSUE TITLE
测试chatglm2的adarola的时候报错如下

### ISSUE THREAD

**Issue by dayu1979** [lyhue1991/torchkeras#27]
不知道是peft的哪个版本才有 AdaLoraConfig，我用的是0.3.0
ImportError: cannot import name 'AdaLoraConfig' from 'peft'

**Comment by dayu1979** [comment]
更新之后peft重启jupyter即可

**Comment by fufeng01** [comment]
执行22步，ds_train = ds_train_raw.map报错，请问遇到了吗
信息如下
![image](https://github.com/lyhue1991/torchkeras/assets/129488076/ca9a8544-109a-4705-9578-38aad640dc43)
