### ISSUE TITLE
torch.nn.modules.module.ModuleAttributeError: 'DataParallel' object has no attribute 'compile'

### ISSUE THREAD

**Issue by bolgxh** [lyhue1991/torchkeras#3]
when I use model = nn.DataParallel(model, device_ids=model_device_ids), I got this Error:torch.nn.modules.module.ModuleAttributeError: 'DataParallel' object has no attribute 'compile'
can you fix this problem, Thank you very much!!

**Comment by maxliubl** [comment]
I had solved this Error by use model = torchkeras.Model(net).
