### ISSUE TITLE
运行chatglm2_AdaLoRA报错

### ISSUE THREAD

**Issue by ddzz0210** [lyhue1991/torchkeras#40]
AttributeError: 'ChatGLMTokenizer' object has no attribute 'build_prompt'

**Comment by lyhue1991** [comment]
拉取最新的chatglm2-6b代码。加群里交流反馈更及时。

**Comment by ddzz0210** [comment]
> 拉取最新的chatglm2-6b代码。加群里交流反馈更及时。

加您的微信啦，还没有通过哦
