### ISSUE TITLE
RuntimeError: Expected is_sm80 to be true, but got false.  

### ISSUE THREAD

**Issue by OldSixOne** [lyhue1991/torchkeras#42]
self.accelerator.backward(loss)   
 RuntimeError: Expected is_sm80 to be true, but got false.  
accelerate=0.21 accelerate=0.20 都不行

**Comment by lyhue1991** [comment]
可能是peft或者什么库的版本问题，自己排查一下。

**Comment by prigioni** [comment]
> self.accelerator.backward(loss) RuntimeError: Expected is_sm80 to be true, but got false. accelerate=0.21 accelerate=0.20 都不行

我也遇到了同样的问题，请问您解决了？
