### ISSUE TITLE
ImportError: cannot import name 'MiniLogCallback' from 'torchkeras.kerascallbacks'

### ISSUE THREAD

**Issue by hhr114** [lyhue1991/torchkeras#46]

**Comment by hhr114** [comment]
建议更新一版 [03，kerasmodel_tuning_demo.ipynb](https://github.com/lyhue1991/torchkeras/blob/master/03%EF%BC%8Ckerasmodel_tuning_demo.ipynb)
已经跑不通了

**Comment by lyhue1991** [comment]
已经更新~

**Comment by hhr114** [comment]
另外想请教一个问题，`wandb.agent(sweep_id, function=train)` 中的train函数一般是无参数的，然后在train函数中进行prepare dataloader, prepare model, fit model几个步骤。如果说我的数据是固定的，不想在每组参数train的过程中重新制作dataloader，那么应该怎么解决呢？我试过往train函数中加默认参数，把全局变量dl_train传给它，但这样wandb会报错`errored: RecursionError('maximum recursion depth exceeded')`，请问大佬对于这样的情况有什么建议的解决办法吗？

**Comment by hhr114** [comment]
破案了，原来是wandb.agent只能在jupyter里使用，写在.py文件里会内存泄露……
