### ISSUE TITLE
cannot import name 'LightModel' from 'torchkeras'

### ISSUE THREAD

**Issue by lwppwl** [lyhue1991/torchkeras#50]
3.9.2版本的torchkeras中运行from torchkeras import LightModel 会出现cannot import name 'LightModel' from 'torchkeras'，之前版本是可以的，最新版LightModel被去除了吗？

**Comment by lyhue1991** [comment]
LightModel is dropped, please use KerasModel instead. 更加好用，功能更完善，兼容性更好~ Pytorch Lightning 的版本兼容性太糟糕了，所以移除了

**Comment by lwppwl** [comment]
@lyhue1991 感谢作者的回复。
