### ISSUE TITLE
BaiChuan13B_NER——transformers.ipynb训练过程中多卡问题

### ISSUE THREAD

**Issue by looperEit** [lyhue1991/torchkeras#53]
keras_model.load_ckpt(ckpt_path) #支持加载微调后的权重继续训练(断点续训)
keras_model.fit(train_data = dl_train,
                val_data = dl_val,
                epochs=100,patience=10,
                monitor='val_loss',mode='min',
                ckpt_path = ckpt_path
               )

在开始微调训练模型时出现问题

> RuntimeError                              Traceback (most recent call last)
> Cell In[39], line 2
>       1 keras_model.load_ckpt(ckpt_path) #支持加载微调后的权重继续训练(断点续训)
> ----> 2 keras_model.fit(train_data = dl_train,
>       3                 val_data = dl_val,
>       4                 epochs=100,patience=10,
>       5                 monitor='val_loss',mode='min',
>       6                 ckpt_path = ckpt_path
>       7                )
> 
> File ~/anaconda3/envs/baichuan13b/lib/python3.9/site-packages/torchkeras/kerasmodel.py:204, in KerasModel.fit(self, train_data, val_data, epochs, ckpt_path, patience, monitor, mode, callbacks, plot, wandb, quiet, mixed_precision, cpu, gradient_accumulation_steps)
>     202 train_epoch_runner = self.EpochRunner(train_step_runner,should_quiet)
>     203 train_metrics = {'epoch':epoch}
> --> 204 train_metrics.update(train_epoch_runner(train_dataloader))
>     206 for name, metric in train_metrics.items():
>     207     self.history[name] = self.history.get(name, []) + [metric]
> 
> File ~/anaconda3/envs/baichuan13b/lib/python3.9/site-packages/torchkeras/kerasmodel.py:77, in EpochRunner.__call__(self, dataloader)
>      75 for step, batch in loop: 
>      76     with self.accelerator.accumulate(self.net):
> ---> 77         step_losses,step_metrics = self.steprunner(batch)   
>      78         step_log = dict(step_losses,**step_metrics)
>      79         for k,v in step_losses.items():
> 
> Cell In[30], line 20, in StepRunner.__call__(self, batch)
>      16 def __call__(self, batch):
>      17     
>      18     #loss
>      19     with self.accelerator.autocast():
> ---> 20         loss = self.net.forward(**batch)[0]
>      22     #backward()
>      23     if self.optimizer is not None and self.stage=="train":
> 
> File ~/anaconda3/envs/baichuan13b/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py:157, in DataParallel.forward(self, *inputs, **kwargs)
>     155 for t in chain(self.module.parameters(), self.module.buffers()):
>     156     if t.device != self.src_device_obj:
> --> 157         raise RuntimeError("module must have its parameters and buffers "
>     158                            "on device {} (device_ids[0]) but found one of "
>     159                            "them on device: {}".format(self.src_device_obj, t.device))
>     161 inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)
>     162 # for forward function without any inputs, empty list and dict will be created
>     163 # so the module can be executed on one device which is the first one in device_ids
> 
> RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cuda:1
> 

这个keras是只支持单卡训练吗？ 我将我的参数放到了双卡上

**Comment by sandboxwy** [comment]
我也是多卡训练报类似错，peft换成lora训练就行，可能是通过peft使用adalora配置时模型参数没有放在同一设备上
