### ISSUE TITLE
大佬你好  transformer那一章节，后面训练的时候用的是CPU。能否改成GPU呢？ 或者怎么改一下可以使用GPU进行训练

### ISSUE THREAD

**Issue by willwilling** [lyhue1991/torchkeras#54]
respect.
麻烦解答一下，多谢哈，辛苦~

**Comment by lyhue1991** [comment]
有GPU就会用GPU，没有GPU就会用CPU，自动的

**Comment by willwilling** [comment]
> 有GPU就会用GPU，没有GPU就会用CPU，自动的

我有GPU的，但是为啥训练的时候只是跑在CPU上了。贼拉慢

**Comment by willwilling** [comment]
<img width="617" alt="image" src="https://github.com/lyhue1991/torchkeras/assets/18168678/fb4ed250-fecf-4d90-95ff-5b7e074ba89b">

**Comment by willwilling** [comment]
<img width="1101" alt="image" src="https://github.com/lyhue1991/torchkeras/assets/18168678/d0a00d8c-487e-4909-b5b5-b0977472a834">



                
(50, 50)
tensor([11,  2,  8,  2,  3, 10,  7,  7,  1,  8,  9,  2,  5,  2,  1,  1,  1,  9,
        13, 10,  6, 10,  6,  7,  6,  6,  1,  5,  3,  9,  7,  9, 10, 12,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]) tensor([11,  2,  8,  2,  3,  6,  8,  3,  9,  5,  5,  4, 10,  6, 10,  9, 10,  9,
        12,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]) 

('<SOS>28230771892521119+06067661539790<EOS><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD>', '<SOS>28236839554060909<EOS><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD><PAD>')
out1:
 tensor([[[ 0.3553,  0.2580,  0.5774, -0.2881],
         [ 0.3343,  0.2578,  0.6262, -0.2681]]], grad_fn=<ViewBackward0>)
out2:
 tensor([[[ 0.3553,  0.2580,  0.5774, -0.2881],
         [ 0.2689,  0.2320,  0.6835, -0.1588]]], grad_fn=<ViewBackward0>)
<<<<<< ⚡️ cuda is used >>>>>>
Cannot execute code, session has been disposed. Please try restarting the Kernel.
The Kernel crashed while executing code in the the current cell or a previous cell. Please review the code in the cell(s) to identify a possible cause of the failure. Click here for more info. View Jupyter log for further details.
input:
744905345112863593+7323038062936802655 

ground truth:
8067943408049666248 

prediction:
8067943408049666248
Could not render content for "application/vnd.jupyter.widget-view+json"
{"model_id":"2201304e23d04bfa9c62fc29821ec2a2","version_major":2,"version_minor":0}
acc= 1.0
inputs:
['<SOS>', '4', '7', '0', '0', '3', '2', '7', '6', '9', '0', '4', '5', '3', '9', '6', '9', '8', '+', '7', '1', '8', '0', '7', '8', '8', '0', '0', '6', '4', '<EOS>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

ground truth:
['<SOS>', '4', '7', '0', '0', '3', '3', '4', '8', '7', '1', '2', '4', '1', '9', '7', '6', '2', '<EOS>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>', '<PAD>'] 

prediction:
['<SOS>', '4', '7', '0', '0', '3', '3', '4', '8', '7', '1', '2', '4', '1', '9', '7', '6', '2', '<EOS>', '<EOS>', '<EOS>', '<EOS>', '<EOS>', '<EOS>', '<EOS>', '<EOS>', '<EOS>', '<EOS>', '<EOS>', '<EOS>', '<EOS>', '<EOS>', '<EOS>', '<EOS>', '<EOS>', '<EOS>', '<EOS>', '<EOS>', '<EOS>', '<EOS>', '<EOS>', '<EOS>', '<EOS>', '<EOS>', '<EOS>', '<EOS>', '<EOS>', '<EOS>', '<EOS>', '<EOS>']

**Comment by willwilling** [comment]
The Kernel crashed while executing code in the the current cell or a previous cell. Please review the code in the cell(s) to identify a possible cause of the failure. Click [here](https://aka.ms/vscodeJupyterKernelCrash) for more info. View Jupyter [log](command:jupyter.viewOutput) for further details.

执行model.fit 会直接crash

**Comment by lyhue1991** [comment]
可能环境有些问题，你先跑一下这个范例看看：
https://github.com/lyhue1991/torchkeras/blob/master/01%EF%BC%8Ckerasmodel_example.ipynb

**Comment by willwilling** [comment]
> 可能环境有些问题，你先跑一下这个范例看看： https://github.com/lyhue1991/torchkeras/blob/master/01%EF%BC%8Ckerasmodel_example.ipynb

<img width="1011" alt="image" src="https://github.com/lyhue1991/torchkeras/assets/18168678/8ddc4a38-dbba-4eff-8bbe-2707004a82dc">

报同样的错误。
硬件版本：cuda11.6
三件套安装命令：
conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 pytorch-cuda=11.6 -c pytorch -c nvidia

**Comment by willwilling** [comment]
<img width="607" alt="image" src="https://github.com/lyhue1991/torchkeras/assets/18168678/bf2bde1c-bf23-4e9b-bcc1-900616eb7a17">

**Comment by willwilling** [comment]
环境问题
再加上网上的指导都不太对。。。真坑
[falses]
pip install torch torchvision torchaudio --pre --extra-index-url https://download.pytorch.org/whl/nightly/cu116

[right]
pip install torch==1.13.1+cu116 torchvision==0.14.1+cu116 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu116

**Comment by lyhue1991** [comment]
OK
