### ISSUE TITLE
对断点续训支持得不太好

### ISSUE THREAD

**Issue by hhr114** [lyhue1991/torchkeras#56]
能否在kerasmodel中添加resume接口，保存ckpt时同时保存epoch、lr_scheduler、optimizer等信息，在resume函数中加载指定路径最新的ckpt，继续在dfhistory后追加训练信息？

**Comment by lyhue1991** [comment]
keras_model.load_ckpt(ckpt_path)后重新训练就可以了。不要搞这些不必要的东西。
