### ISSUE TITLE
运行ChatGLM2_AdaLoRA——transformers.py 时定义模型报错Target modules ['query', 'value'] not found in the base model. 

### ISSUE THREAD

**Issue by wendyDing1102** [lyhue1991/torchkeras#58]

**Comment by MarshalXu** [comment]
chatglm-lora微调时，targetmodule有这么几个 query_key_value,dense_h_to_4h,dense_4h_to_h,dense ，一般是选择query_key_value，你这个是module名配置错了吧。

**Comment by DearAmber** [comment]
@MarshalXu  感恩，按照你的方法解决了！奇怪之前没有这个问题

**Comment by zx12671** [comment]
@DearAmber  碰到同样的问题， 请问是改成target_modules=["query_key_value"] 吗
