### ISSUE TITLE
求问：fit_ddp方法报ProcessExitedException: process 0 terminated with signal SIGSEGV错误

### ISSUE THREAD

**Issue by muyunchengbi** [lyhue1991/torchkeras#60]
Ubuntu21.10，Python3.10.12，torchkeras-3.9.4，accelerate-0.23.0_dev0环境
fit_ddp()方法训练时没有问题，每次训练结束后，都会报：ProcessExitedException: process 0 terminated with signal SIGSEGV错误，请问是什么原因呀？

**Comment by lyhue1991** [comment]
与accelerate有关的问题，请到accelerate仓库下寻求帮助。

**Comment by muyunchengbi** [comment]
收到！谢谢您的回复！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月6日(周三) 上午10:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [lyhue1991/torchkeras] 求问：fit_ddp方法报ProcessExitedException: process 0 terminated with signal SIGSEGV错误 (Issue #60)




 
与accelerate有关的问题，请到accelerate仓库下寻求帮助。
